pawcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('vets/', include('vets.urls')),
    path('pet_owners/', include('pet_owners.urls')),
    path('recreation/', include('recreation.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS[0])

pet_owners/urls.py
from django.urls import path
from .views import register_owner, login_owner, user_dashboard

app_name = 'pet_owners'

urlpatterns = [
    path('login/', login_owner, name='login'),
    path('register/', register_owner, name='register'),
    path('dashboard/<int:owner_id>/', user_dashboard, name='user_dashboard'),
]

vets/urls.py
from django.urls import path
from .views import doctor_dashboard, register_vet, login_vet, vet_search, vet_results, app_slots

app_name = 'vets'

urlpatterns = [
    path('dashboard/<int:vet_id>/', doctor_dashboard, name='doctor_dashboard'),
    path('register/', register_vet, name='register'),
    path('login/', login_vet, name='login'),
    path('vet_search/', vet_search, name='vet_search'),
    path('vet_results/', vet_results, name='vet_results'),
    path('app_slots/', app_slots, name='app_slots'),
]

pet_owners/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.db import models
from django.apps import apps


class PetOwnerManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class PetOwner(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True, null=False)
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=200, null=True)
    street = models.CharField(max_length=200, null=True)
    phone_number = models.CharField(max_length=15, null=True)
    email = models.EmailField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    groups = models.ManyToManyField(Group, related_name='pet_owners_users')
    user_permissions = models.ManyToManyField(
        Permission, related_name='pet_owners_user_permissions')

    objects = PetOwnerManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.name


class Pet(models.Model):
    owner = models.ForeignKey(
        PetOwner, on_delete=models.CASCADE, related_name='pets')
    vet = models.ForeignKey('vets.Vet', on_delete=models.CASCADE,
                            null=True, related_name='pets')
    name = models.CharField(max_length=100, null=False)
    breed = models.CharField(max_length=100, null=False, blank=True)
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices=[
                              ('male', 'Male'), ('female', 'Female')])
    weight = models.FloatField(null=True, blank=True)
    vaccinations = models.TextField(null=True, blank=True)
    medical_notes = models.TextField(null=True, blank=True)
    previous_reports = models.TextField(null=True, blank=True)
    additional_comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

pet_owners/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import PetOwner, Pet


class PetOwnerCreationForm(UserCreationForm):
    class Meta:
        model = PetOwner
        fields = ('username', 'email', 'password1', 'password2')


class PetOwnerLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=("Password"), strip=False, widget=forms.PasswordInput)


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'breed', 'age', 'gender', 'weight', 'vaccinations',
                  'medical_notes', 'previous_reports', 'additional_comments']

pet_owners/views.py
# pet_owners/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import PetOwnerCreationForm, PetOwnerLoginForm, PetForm
from .models import PetOwner, Pet


def register_owner(request):
    if request.method == 'POST':
        form = PetOwnerCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()

            # Authenticate the user
            user = authenticate(
                username=form.cleaned_data['username'], password=form.cleaned_data['password1'])

            if user is not None:
                login(request, user,
                      backend='pet_owners.auth_backends.PetOwnersBackend')
                return redirect('pet_owners:user_dashboard', owner_id=user.id)
            else:
                print("Authentication failed")  # Debug statement
        else:
            print("Form is invalid")  # Debug statement
            print(form.errors)  # Print form errors for debugging
    else:
        form = PetOwnerCreationForm()
    return render(request, 'prl.html', {'form': form, 'login_form': PetOwnerLoginForm()})


def login_owner(request):
    if request.method == 'POST':
        form = PetOwnerLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user,
                      backend='pet_owners.auth_backends.PetOwnersBackend')
                return redirect('pet_owners:user_dashboard', owner_id=user.id)
    else:
        form = PetOwnerLoginForm()
    return render(request, 'prl.html', {'login_form': form, 'form': PetOwnerCreationForm()})


@login_required
def user_dashboard(request, owner_id):
    owner = PetOwner.objects.get(id=owner_id)  # Fetch the PetOwner instance

    if request.method == 'POST':
        form = PetForm(request.POST)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.owner = owner  # Set the pet owner to the PetOwner instance
            pet.save()
            # Redirect to the same page after saving
            return redirect('pet_owners:user_dashboard', owner_id=owner.id)
    else:
        form = PetForm()

    pets = Pet.objects.filter(owner=owner)  # Filter pets by the owner

    return render(request, 'user_dashboard.html', {'form': form, 'pets': pets, 'owner': owner})

pet_owners/templates/prl.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pawcare - Login & Signup</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/prl.css' %}">
</head>

<body class="fadeIn">
    <header>
        <div class="logo">Pawcare</div>
        <h1 id="head"></h1>
        <nav>
            <a href="{% url 'home' %}">Home</a>
        </nav>
    </header>

    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked>
            <label for="tab-1" class="tab">Sign In</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up">
            <label for="tab-2" class="tab">Sign Up</label>
            <div class="login-form">
                <div class="sign-in-htm">
                    <form method="post" action="{% url 'pet_owners:login' %}">
                        {% csrf_token %}
                        <div class="group">
                            {{ login_form.username.errors }}
                            <label for="user" class="label">Username</label>
                            <input id="user" type="text" class="input" name="username" required>
                        </div>
                        <div class="group">
                            {{ login_form.password.errors }}
                            <label for="pass" class="label">Password</label>
                            <input id="pass" type="password" class="input" data-type="password" name="password"
                                required>
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign In">
                        </div>
                    </form>
                    <div class="hr"></div>
                </div>
                <div class="sign-up-htm">
                    <form method="post" action="{% url 'pet_owners:register' %}">
                        {% csrf_token %}
                        <div class="group">
                            <label for="new-user" class="label">Username</label>
                            {{ form.username.errors }}
                            <input id="new-user" type="text" class="input" name="username" required>
                        </div>
                        <div class="group">
                            <label for="email" class="label">Email Address</label>
                            {{ form.email.errors }}
                            <input id="email" type="email" class="input" name="email" required>
                        </div>
                        <div class="group">
                            <label for="new-pass" class="label">Password</label>
                            {{ form.password1.errors }}
                            <input id="new-pass" type="password" class="input" data-type="password" name="password1"
                                required>
                        </div>
                        <div class="group">
                            <label for="repeat-pass" class="label">Repeat Password</label>
                            {{ form.password2.errors }}
                            <input id="repeat-pass" type="password" class="input" data-type="password" name="password2"
                                required>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign Up">
                        </div>
                    </form>
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <label for="tab-1">Already Member?</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

pet_owners/templates/user_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PawCare - Pet Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/user_dashboard.css' %}">
</head>

<body>

    <header>
        <div class="logo">Pawcare</div>
        <nav>
            <a href="{% url 'home' %}">Home</a>
        </nav>
        <section>
            <div class="video">
            </div>
        </section>
    </header>


    <div class="container">
        {% if pets %}
        <h2>Pet Information</h2>
        {% for pet in pets %}
        <p><strong>Name:</strong> {{ pet.name }}</p>
        <p><strong>Breed:</strong> {{ pet.breed }}</p>
        <p><strong>Age:</strong> {{ pet.age }}</p>
        <p><strong>Gender:</strong> {{ pet.gender }}</p>
        <p><strong>Weight:</strong> {{ pet.weight }}</p>
        <p><strong>Vaccination History:</strong> {{ pet.vaccinations }}</p>
        <p><strong>Medical Notes:</strong> {{ pet.medical_notes }}</p>
        <p><strong>Previous Reports:</strong> {{ pet.previous_reports }}</p>
        <p><strong>Additional Comments:</strong> {{ pet.additional_comments }}</p>
        {% endfor %}
        {% else %}
        <p>You have no pets added yet.</p>
        {% endif %}
        <form method="post" action="{% url 'pet_owners:user_dashboard' owner.id %}">
            {% csrf_token %}
            <label for="name">Pet Name</label>
            <input type="text" id="name" name="name" required>

            <label for="breed">Breed</label>
            <input type="text" id="breed" name="breed">

            <label for="age">Age</label>
            <input type="number" id="age" name="age" required>

            <label for="gender">Gender</label>
            <select id="gender" name="gender">
                <option value="male">Male</option>
                <option value="female">Female</option>
            </select>

            <label for="weight">Weight (kg)</label>
            <input type="number" id="weight" name="weight">

            <label for="vaccinations">Vaccination History</label>
            <textarea id="vaccinations" name="vaccinations" rows="4"></textarea>

            <label for="medical_notes">Medical Notes</label>
            <textarea id="medical_notes" name="medical_notes" rows="4"></textarea>

            <label for="previous_reports">Previous Medical Reports</label>
            <textarea id="previous_reports" name="previous_reports" rows="4"></textarea>
            <!-- Apply class "upload-button" to style the Upload Files button
            <button type="button" class="upload-button">Upload Files</button> -->

            <label for="additional_comments">Additional Comments</label>
            <textarea id="additional_comments" name="additional_comments" rows="4"></textarea>

            <!-- Apply class "add-pet-button" to style the Add Pet button -->
            <button type="submit" class="add-pet-button">Add Pet</button>
        </form>
    </div>

</body>

</html>