pawcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('vets/', include('vets.urls')),
    path('pet_owners/', include('pet_owners.urls')),
    path('recreation/', include('recreation.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS[0])

pet_owners/urls.py
from django.urls import path
from .views import register_owner, login_owner, user_dashboard

app_name = 'pet_owners'

urlpatterns = [
    path('login/', login_owner, name='login'),
    path('register/', register_owner, name='register'),
    path('dashboard/<int:owner_id>/', user_dashboard, name='user_dashboard'),
]

vets/urls.py
from django.urls import path
from .views import doctor_dashboard, register_vet, login_vet, vet_search, vet_results, app_slots

app_name = 'vets'

urlpatterns = [
    path('dashboard/<int:vet_id>/', doctor_dashboard, name='doctor_dashboard'),
    path('register/', register_vet, name='register'),
    path('login/', login_vet, name='login'),
    path('vet_search/', vet_search, name='vet_search'),
    path('vet_results/', vet_results, name='vet_results'),
    path('app_slots/', app_slots, name='app_slots'),
]

vets/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.db import models
from pet_owners.models import Pet


class VetManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        email = self.normalize_email(username)
        user = self.model(username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class Vet(AbstractBaseUser, PermissionsMixin):
    username = models.EmailField(unique=True, null=False)
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    street = models.CharField(max_length=200, null=True)
    PLZ = models.IntegerField(null=True)
    phone_number = models.CharField(max_length=15, null=True)
    email = models.EmailField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    groups = models.ManyToManyField(Group, related_name='vet_users')
    user_permissions = models.ManyToManyField(
        Permission, related_name='vet_user_permissions')

    objects = VetManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.name


class Appointments(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE,
                            null=True, related_name='pet_appointments')
    vet = models.ForeignKey(Vet, on_delete=models.CASCADE,
                            related_name='vet_appointments')
    date = models.DateField()
    time = models.TimeField()
    complaints = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Appointment with {self.vet.name} for {self.pet.name} on {self.date} at {self.time}"

vets/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Vet, Appointments
from pet_owners.models import Pet, PetOwner


class VetCreationForm(UserCreationForm):
    class Meta:
        model = Vet
        fields = ('username', 'name', 'password1', 'password2')


class VetLoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=("Password"), strip=False, widget=forms.PasswordInput)


class AppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        vet = kwargs.pop('vet', None)
        super(AppointmentForm, self).__init__(*args, **kwargs)
        if vet:
            self.fields['pet'].queryset = Pet.objects.filter(
                pet_appointments__vet=vet).distinct()

    class Meta:
        model = Appointments
        fields = ['pet', 'date', 'time', 'complaints']


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'breed', 'age', 'gender']


class PetOwnerCreationForm(forms.ModelForm):
    class Meta:
        model = PetOwner
        fields = ['name', 'username', 'email', 'phone_number']

vets/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import VetCreationForm, VetLoginForm, AppointmentForm, PetForm, PetOwnerCreationForm
from .models import Vet, Appointments
from pet_owners.models import Pet, PetOwner
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils import timezone


def register_vet(request):
    if request.method == 'POST':
        form = VetCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()

            # Set the backend for the user
            user.backend = 'vets.auth_backends.VetBackend'

            # Authenticate the user
            user = authenticate(
                username=form.cleaned_data['username'], password=form.cleaned_data['password1'], backend=user.backend)

            if user is not None:
                login(request, user, backend='vets.auth_backends.VetBackend')
                return redirect('vets:doctor_dashboard', vet_id=user.id)
    else:
        form = VetCreationForm()
    return render(request, 'drl.html', {'form': form, 'login_form': VetLoginForm()})


def login_vet(request):
    if request.method == 'POST':
        form = VetLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user, backend='vets.auth_backends.VetBackend')
                return redirect('vets:doctor_dashboard', vet_id=user.id)
    else:
        form = VetLoginForm()
    return render(request, 'drl.html', {'login_form': form, 'form': VetCreationForm()})


@login_required
def doctor_dashboard(request, vet_id):
    vet = Vet.objects.get(id=vet_id)
    appointments = Appointments.objects.filter(vet=vet)

    # Calculate total number of pets
    total_pets = Pet.objects.filter(vet=vet).count()

    # Calculate number of appointments for today
    today = timezone.now().date()
    appointments_today = Appointments.objects.filter(
        vet=vet, date=today).count()

    if request.method == 'POST':
        if 'schedule_appointment' in request.POST:
            pet_id = request.POST.get('pet')
            appointment_date = request.POST.get('appointmentDate')
            appointment_time = request.POST.get('appointmentTime')
            reason = request.POST.get('reason')
            pet = Pet.objects.get(id=pet_id)

            appointment = Appointments.objects.create(
                pet=pet,
                vet=vet,
                date=appointment_date,
                time=appointment_time,
                complaints=reason,
            )
            appointment.save()

            return redirect('vets:doctor_dashboard', vet_id=vet.id)

        elif 'add_patient' in request.POST:
            pet_owner_form = PetOwnerCreationForm(request.POST)
            pet_form = PetForm(request.POST)

            if pet_owner_form.is_valid() and pet_form.is_valid():
                pet_owner = pet_owner_form.save(commit=False)
                pet_owner.set_password("Pawcare_temp123")
                pet_owner.save()

                pet = pet_form.save(commit=False)
                pet.name = request.POST.get('pet_name')
                pet.owner = pet_owner
                pet.vet = vet
                pet.save()

                return redirect('vets:doctor_dashboard', vet_id=vet.id)
    else:
        appointment_form = AppointmentForm(vet=vet)
        pet_owner_form = PetOwnerCreationForm()
        pet_form = PetForm()

    pets = Pet.objects.filter(vet=vet).distinct()
    return render(request, 'doctor_dashboard.html', {
        'appointment_form': appointment_form,
        'pet_owner_form': pet_owner_form,
        'pet_form': pet_form,
        'appointments': appointments,
        'pets': pets,
        'vet': vet,
        'total_pets': total_pets,
        'appointments_today': appointments_today,
    })


def vet_search(request):
    vets = Vet.objects.all()
    return render(request, 'vet_search.html', {'vets': vets})


def vet_results(request):
    location_query = request.GET.get('location', '')
    query = Q()

    if location_query:
        query &= (Q(city__icontains=location_query) |
                  Q(state__icontains=location_query) |
                  Q(PLZ__icontains=location_query))

    if not location_query:
        results = Vet.objects.all().order_by('city')
    else:
        results = Vet.objects.filter(query).order_by(
            'city') if query else Vet.objects.none()

    return render(request, 'vet_results.html', {'results': results})


def app_slots(request):
    return render(request, 'app_slots.html')

vets/templates/app_slots.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appointment Slots</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/app_slots.css' %}">
</head>
<header>
    <div class="logo">Pawcare</div>
    <nav>
        <a href="{%url 'home' %}">Home</a>
    </nav>
</header>

<body>
    <div class="container">
        <h1>Appointment Scheduler</h1>
        <div class="appointment-cards">
            <div class="card">
                <h2>Slot 1</h2>
                <p>Date: July 1, 2024</p>
                <button>Book</button>
            </div>
            <div class="card">
                <h2>Slot 2</h2>
                <p>Date: July 2, 2024</p>
                <button>Book</button>
            </div>
            <!-- Add more cards as needed -->
        </div>
    </div>
</body>

</html>

vets/templates/doctor_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor's Dashboard</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/doctor_dashboard.css' %}">
</head>

<body>
    <nav>
        <a href="#" onclick="showTab('dashboard')">Dashboard</a>
        <a href="#" onclick="showTab('patients')">Patients</a>
        <a href="#" onclick="showTab('appointments')">Appointments</a>
    </nav>

    <header>
        <h1>Hello Dr. {{ vet.name }}</h1>
        <div class="header-right">
            <a href="{% url 'home' %}" class="home-icon"><i class="fas fa-home"></i></a>
            <i class="fas fa-user profile-icon" onclick="toggleModal()"></i>
        </div>
    </header>

    <div class="dashboard-container">
        <div id="dashboard" class="tab-content active">
            <div class="statistics-section">
                <h2>Statistics</h2>
                <div class="statistics-item">
                    <span>Total Patients:</span>
                    <span id="totalPatients">{{ total_pets }}</span>
                </div>
                <div class="statistics-item">
                    <span>Appointments Today:</span>
                    <span id="appointmentsToday">{{ appointments_today }}</span>
                </div>
                <div class="chart-container" id="barChartContainer"></div>
                <div class="table-container">
                    <h3>Appointment Details</h3>
                    <table id="appointmentTable">
                        <thead>
                            <tr>
                                <th>Patient Name</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Reason</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for appointment in appointments %}
                            <tr>
                                <td>{{ appointment.pet.name }}</td>
                                <td>{{ appointment.date }}</td>
                                <td>{{ appointment.time }}</td>
                                <td>{{ appointment.complaints }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div id="patients" class="tab-content">
            <div class="form-container">
                <h2>Patient Details</h2>
                <table id="patientTable">
                    <thead>
                        <tr>
                            <th>Pet Name</th>
                            <th>Breed</th>
                            <th>Gender</th>
                            <th>Age</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for pet in pets %}
                        <tr>
                            <td>{{ pet.name }}</td>
                            <td>{{ pet.breed }}</td>
                            <td>{{ pet.gender }}</td>
                            <td>{{ pet.age }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <h2>Add Patient Information</h2>
                <form id="patientForm" method="post" action="{% url 'vets:doctor_dashboard' vet.id %}">
                    {% csrf_token %}
                    {{ pet_owner_form.non_field_errors }}
                    <label for="name">Pet Owner Name:</label>
                    {{ pet_owner_form.name.errors }}
                    <input type="text" id="name" name="name" placeholder="John Doe" required>

                    <label for="username">Username:</label>
                    {{ pet_owner_form.username.errors }}
                    <input type="text" id="username" name="username" placeholder="johndoe" required>

                    <label for="email">Email:</label>
                    {{ pet_owner_form.email.errors }}
                    <input type="email" id="email" name="email" placeholder="example@example.com" required>

                    <label for="phone_number">Contact Number:</label>
                    {{ pet_owner_form.phone_number.errors }}
                    <input type="tel" id="phone_number" name="phone_number" placeholder="555-555-5555" required>

                    {{ pet_form.non_field_errors }}
                    <label for="pet_name">Pet Name:</label>
                    {{ pet_form.name.errors }}
                    <input type="text" id="pet_name" name="pet_name" placeholder="Max" required>

                    <label for="breed">Breed:</label>
                    {{ pet_form.breed.errors }}
                    <input type="text" id="breed" name="breed" placeholder="Golden Retriever" required>

                    <label for="age">Age:</label>
                    {{ pet_form.age.errors }}
                    <input type="number" id="age" name="age" placeholder="30" required>

                    <label for="gender">Gender:</label>
                    {{ pet_form.gender.errors }}
                    <select id="gender" name="gender" required>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>

                    <button type="submit" name="add_patient">Submit</button>
                </form>
            </div>
        </div>

        <div id="appointments" class="tab-content">
            <div class="form-container">
                <h2>Schedule an Appointment</h2>
                <form id="appointmentForm" method="post" action="{% url 'vets:doctor_dashboard' vet.id %}">
                    {% csrf_token %}
                    <label for="pet">Patient Name:</label>
                    <select id="pet" name="pet" required>
                        <option value="" disabled selected>Select Patient</option>
                        {% for pet in pets %}
                        <option value="{{ pet.id }}">{{ pet.name }}</option>
                        {% endfor %}
                    </select>

                    <label for="appointmentDate">Appointment Date:</label>
                    <input type="date" id="appointmentDate" name="appointmentDate" required>

                    <label for="appointmentTime">Appointment Time:</label>
                    <input type="time" id="appointmentTime" name="appointmentTime" required>

                    <label for="reason">Reason for Appointment:</label>
                    <input type="text" id="reason" name="reason" placeholder="Check-up" required>

                    <button type="submit" name="schedule_appointment">Submit</button>
                </form>
            </div>
        </div>
    </div>

    <div id="profileModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="toggleModal()">&times;</span>
            <div class="profile-section">
                <h2>Dr. {{ vet.name }}'s Profile</h2>
                <p>Name: {{ vet.name }}</p>
                <p>Email: {{ vet.email }}</p>
                <p>Phone: {{ vet.phone_number }}</p>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        // JavaScript for toggling tabs
        function showTab(tabId) {
            const tabs = document.getElementsByClassName('tab-content');
            for (let i = 0; i < tabs.length; i++) {
                tabs[i].classList.remove('active');
            }
            document.getElementById(tabId).classList.add('active');
        }

        // JavaScript for toggling modal
        function toggleModal() {
            const modal = document.getElementById('profileModal');
            if (modal.style.display === "block") {
                modal.style.display = "none";
            } else {
                modal.style.display = "block";
            }
        }
    </script>
</body>

</html>

vets/templates/drl.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pawcare - Doctor Login & Signup</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/drl.css' %}">
</head>

<body>
    <header>
        <div class="logo">Pawcare</div>
        <h1 id="head"></h1>
        <nav>
            <a href="{%url 'home' %}">Home</a>
        </nav>
        <h1 class="intro">Are you a Veterinarian? Register with us now to access EHR services.</h1>
    </header>

    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked>
            <label for="tab-1" class="tab">Sign In</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up">
            <label for="tab-2" class="tab">Sign Up</label>
            <div class="login-form">
                <div class="sign-in-htm">
                    <form method="post" action="{% url 'vets:login' %}">
                        {% csrf_token %}
                        <div class="group">
                            {{ login_form.username.errors }}
                            <label for="user" class="label">Email Address</label>
                            <input id="user" type="text" class="input" name="username" required>
                        </div>
                        <div class="group">
                            {{ login_form.password.errors }}
                            <label for="pass" class="label">Password</label>
                            <input id="pass" type="password" class="input" data-type="password" name="password"
                                required>
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign In">
                        </div>
                    </form>
                    <div class="hr"></div>
                </div>

                <div class="sign-up-htm">
                    <form method="post" action="{% url 'vets:register' %}">
                        {% csrf_token %}
                        <div class="group">
                            <label for="email" class="label">Email Address</label>
                            {{ form.username.errors }}
                            <input id="email" type="email" class="input" name="username" required>
                        </div>
                        <div class="group">
                            <label for="new-user" class="label">Name</label>
                            {{ form.name.errors }}
                            <input id="new-user" type="text" class="input" name="name" required>
                        </div>
                        <div class="group">
                            <label for="new-pass" class="label">Password</label>
                            {{ form.password1.errors }}
                            <input id="new-pass" type="password" class="input" data-type="password" name="password1"
                                required>
                        </div>
                        <div class="group">
                            <label for="repeat-pass" class="label">Repeat Password</label>
                            {{ form.password2.errors }}
                            <input id="repeat-pass" type="password" class="input" data-type="password" name="password2"
                                required>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign Up">
                        </div>
                    </form>
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <label for="tab-1">Already Member?</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

vets/templates/vet_results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clinic Search Results</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/vet_results.css' %}">
</head>

<body>
    <header>
        <div class="logo">Pawcare</div>
        <h1 id="head"></h1>
        <nav>
            <a href="{% url 'vets:vet_search'%}">Back to Search</a>
            <a href="{%url 'home' %}">Home</a>
        </nav>
    </header>

    <div class="container">
        <h1>Vet Finder</h1>
        <div class="appointment-cards">
            {% if results %}
            {% for vet in results %}
            <div class="card">
                <div class="clinic-name"><strong>{{ vet.name }}</strong></div>
                <div class="clinic-address">{{ vet.street }}, {{ vet.city }}</div>
                <div class="clinic-state">{{ vet.PLZ }}, {{ vet.state }}</div>
                <div class="clinic-phone">{{ vet.phone_number }}</div>
                {% if vet.email %}
                <div class="clinic-email">{{ vet.email }}</div>
                {% endif %}
                <div class="warning-card">
                    This doctor is not registered with Pawcare, but here's their contact number: {{ vet.phone_number }}
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No clinics found.</p>
            {% endif %}
        </div>
    </div>
</body>

</html>

vets/templates/vet_search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pawcare</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Forum&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/vet_search.css' %}">
    <style>

    </style>
</head>

<body class="fadeIn">
    <div class="background"></div>
    <div class="logo">Pawcare</div>
    <nav>
        <a href="{% url 'pet_owners:register'%}">Pet Login/Register</a>
        <a href="{% url 'home'%}">Home</a>
    </nav>
    <h1 id="head">Search for vets near You</h1>
    <div class="s01">
        <form action="{% url 'vets:vet_results' %}" method="get">
            <div class="inner-form">
                <div class="input-field second-wrap">
                    <input id="location" type="text" placeholder="Location" name="location">
                </div>
                <div class="input-field third-wrap">
                    <button class="btn-search" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
    <div class="cta-container">
        <p>Are You a Veterinarian? We've made it easier for you too!</p>
        <a href="{% url 'vets:register'%}" class="cta-button">Get Started with Pawcare</a>
    </div>
</body>

</html>