pawcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('vets/', include('vets.urls')),
    path('pet_owners/', include('pet_owners.urls')),
    path('recreation/', include('recreation.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS[0])

pet_owners/urls.py
from django.urls import path
from .views import register_owner, login_owner, user_dashboard

app_name = 'pet_owners'

urlpatterns = [
    path('login/', login_owner, name='login'),
    path('register/', register_owner, name='register'),
    path('dashboard/<int:owner_id>/', user_dashboard, name='user_dashboard'),
]

recreation/urls.py
from django.urls import path
from .views import rec_search, rec_results

app_name = 'recreation'

urlpatterns = [
    path('rec_search/', rec_search, name='rec_search'),
    path('rec_results/', rec_results, name='rec_results')
]

vets/urls.py
from django.urls import path
from .views import doctor_dashboard, register_vet, login_vet, vet_search, vet_results, app_slots

app_name = 'vets'

urlpatterns = [
    path('dashboard/<int:vet_id>/', doctor_dashboard, name='doctor_dashboard'),
    path('register/', register_vet, name='register'),
    path('login/', login_vet, name='login'),
    path('vet_search/', vet_search, name='vet_search'),
    path('vet_results/', vet_results, name='vet_results'),
    path('app_slots/', app_slots, name='app_slots'),
]

recreation/models.py
from django.db import models


class Recreation(models.Model):
    CATEGORY_CHOICES = [
        ('trail', 'Dog Trail'),
        ('park', 'Dog Park'),
        ('grooming', 'Grooming Service'),
        ('boarding', 'Boarding House'),
        ('care', 'Day Care'),
    ]

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    street = models.CharField(max_length=200, blank=True)
    PLZ = models.IntegerField(null=True)
    website = models.URLField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.name

recreation/views.py
from django.shortcuts import render
from .models import Recreation
from django.db.models import Q


def rec_search(request):
    activities = Recreation.objects.all()
    return render(request, 'rec_search.html', {'activities': activities})


def rec_results(request):
    search_query = request.GET.get('search', '')
    location_query = request.GET.get('location', '')

    query = Q()

    if search_query:
        category_matches = [
            value for value, display in Recreation.CATEGORY_CHOICES if search_query in display.lower()
        ]

        query &= (Q(name__icontains=search_query) |
                  Q(category__in=category_matches) |
                  Q(category__icontains=search_query))
    if location_query:
        query &= (Q(city__icontains=location_query) |
                  Q(state__icontains=location_query) |
                  Q(PLZ__icontains=location_query))

    if not search_query and not location_query:
        results = Recreation.objects.all().order_by('city')
    else:
        results = Recreation.objects.filter(query).order_by(
            'city') if query else Recreation.objects.none()

    return render(request, 'rec_results.html', {'results': results})

recreation/templates/rec_results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recreational Activities Search Results</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/rec_results.css' %}">
</head>

<body>
    <header>
        <div class="logo">Pawcare</div>
        <h1 id="head"></h1>
        <nav>
            <a href="{%url 'recreation:rec_search' %}">Back to Search</a>
            <a href="{%url 'home' %}">Home</a>
        </nav>
    </header>

    <div class="container">
        <h1>Recreational Locations</h1>
        <div class="appointment-cards">
            {% if results %}
            {% for recreation in results %}
            <div class="card">
                <div class="clinic-name"><strong>{{ recreation.name }}</strong></div>
                <div class="clinic-name">{{ recreation.get_category_display }}</div>
                <div class="clinic-address">{{ recreation.street }}, {{ recreation.city }}</div>
                <div class="clinic-state">{{ recreation.PLZ }}, {{ recreation.state }}</div>
                {% if recreation.email %}
                <div class="clinic-phone">{{ recreation.phone_number }}</div>
                {% endif %}
                {% if recreation.email %}
                <div class="clinic-email">{{ recreation.email }}</div>
                {% endif %}
            </div>
            {% endfor %}
            {% else %}
            <p>No places found.</p>
            {% endif %}
        </div>
    </div>
</body>

</html>

recreation/templates/rec_search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pawcare</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Forum&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/rec_search.css' %}">
    <style>

    </style>
</head>

<body class="fadeIn">
    <div class="background"></div>
    <div class="logo">Pawcare</div>
    <nav>
        <a href="{% url 'pet_owners:register'%}">Pet Login/Register</a>
        <a href="{% url 'home'%}">Home</a>
    </nav>
    <h1 id="head">Search for Boarding Houses and/or Recreational Areas near You</h1>
    <div class="s01">
        <form action="{% url 'recreation:rec_results' %}" method="get">
            <div class="inner-form">
                <div class="input-field first-wrap">
                    <input id="search" type="text" placeholder="Name, Category" name="search">
                </div>
                <div class="input-field second-wrap">
                    <input id="location" type="text" placeholder="Location" name="location">
                </div>
                <div class="input-field third-wrap">
                    <button class="btn-search" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</body>

</html>